### ISSUE TITLE
Python UnicodeDecodeError

### ISSUE THREAD

**Issue by ramoneb** [cpb-/yocto-cooker#147]
When I tried to cook for the first time I got this error:

`# Downloading source from  git://github.com/meta-qt5/meta-qt5
Traceback (most recent call last):
  File "/usr/local/bin/cooker", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/cooker/cooker.py", line 1034, in main
    CookerCall()
  File "/usr/local/lib/python3.7/dist-packages/cooker/cooker.py", line 966, in __init__
    self.clargs.func()  # call function of selected command
  File "/usr/local/lib/python3.7/dist-packages/cooker/cooker.py", line 993, in cook
    self.commands.update()
  File "/usr/local/lib/python3.7/dist-packages/cooker/cooker.py", line 418, in update
    self.update_source(source)
  File "/usr/local/lib/python3.7/dist-packages/cooker/cooker.py", line 454, in update_source
    self.update_directory_initial(method, local_dir, remote_dir, branch, rev)
  File "/usr/local/lib/python3.7/dist-packages/cooker/cooker.py", line 482, in update_directory_initial
    fatal_error('Unable to clone {}: {}'.format(remote_dir, complete.stderr.decode('ascii')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 98: ordinal not in range(128)
`
my configuration is:
`uname -a
Linux dev3 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64 GNU/Linux`

I fix it by changing:
/usr/local/lib/python3.7/dist-packages/cooker/cooker.py
`482: fatal_error('Unable to clone {}: {}'.format(remote_dir, complete.stderr.decode('ascii')))`
to 
`482: fatal_error('Unable to clone {}: {}'.format(remote_dir, complete.stderr..decode('utf-8', errors='replace')))`

**Comment by MarcHLuehr** [comment]
This one also catches me sometimes but rarely. I have the changes here: #156
